"""Machine-stable identifiers shared by pattern-engine phases."""

from enum import StrEnum


class PatternClass(StrEnum):
    TREND = "TREND"
    BASE = "BASE"
    BREAKOUT = "BREAKOUT"
    PULLBACK = "PULLBACK"
    COMPRESSION = "COMPRESSION"
    MOMENTUM = "MOMENTUM"
    FAILURE = "FAILURE"


    REVERSAL = 'REVERSAL'
    CONTINUATION = 'CONTINUATION'
    HARMONIC = 'HARMONIC'
    CANDLESTICK = 'CANDLESTICK'


class PatternState(StrEnum):
    DETECTED = "DETECTED"
    FORMING = "FORMING"
    MATURE = "MATURE"
    READY = "READY"
    TRIGGERED = "TRIGGERED"
    CONFIRMED = "CONFIRMED"
    FAILED = "FAILED"
    INVALIDATED = "INVALIDATED"
    EXPIRED = "EXPIRED"


class PatternEventType(StrEnum):
    PATTERN_DETECTED = "PATTERN_DETECTED"
    STATE_CHANGED = "STATE_CHANGED"
    PIVOT_UPDATED = "PIVOT_UPDATED"
    QUALITY_CHANGED = "QUALITY_CHANGED"
    MATURITY_CHANGED = "MATURITY_CHANGED"
    TRIGGERED = "TRIGGERED"
    CONFIRMED = "CONFIRMED"
    FAILED = "FAILED"
    INVALIDATED = "INVALIDATED"
    EXPIRED = "EXPIRED"


class SwingType(StrEnum):
    HIGH = "HIGH"
    LOW = "LOW"


class ZoneType(StrEnum):
    RESISTANCE = "RESISTANCE"
    SUPPORT = "SUPPORT"


class ImportJobType(StrEnum):
    EQUITY_MASTER = "EQUITY_MASTER"
    EQUITY_CLASSIFICATION = "EQUITY_CLASSIFICATION"
    HISTORY_BACKFILL = "HISTORY_BACKFILL"
    CORPORATE_ACTION_BACKFILL = "CORPORATE_ACTION_BACKFILL"
    DAILY_DELTA = "DAILY_DELTA"
    ADJUSTMENT_REBUILD = "ADJUSTMENT_REBUILD"
    FEATURE_REBUILD = "FEATURE_REBUILD"
    PATTERN_SCAN = "PATTERN_SCAN"


class ImportStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


# Stable public inventory emitted by the production detector pipeline.
SUPPORTED_PATTERN_TYPES = (
    'REV-DBOT', 'REV-DTOP', 'REV-IHS', 'REV-HS', 'REV-CUP',
    'CONT-FLAG-BULL', 'CONT-FLAG-BEAR', 'CONT-TRI-ASC', 'CONT-TRI-DESC',
    'CONT-TRI-SYM', 'CONT-WEDGE-FALL', 'CONT-WEDGE-RISE', 'CONT-RECT',
    'HARM-ABCD', 'HARM-GARTLEY', 'HARM-BAT', 'HARM-BUTTERFLY',
    'HARM-CRAB', 'HARM-CYPHER', 'HARM-SHARK', 'HARM-5O',
    "BASE-VCP", "BASE-FLAT", "BASE-52WH", "BASE-TIGHT",
    "BRK-RANGE", "BRK-52WH", "BRK-ATH", "BRK-MULTIY",
    "PB-BRKRET", "PB-EMA20", "PB-SMA50",
    "TREND-HHHL", "TREND-S2", "TREND-MA",
    "COMP-NR7", "COMP-IB", "COMP-ATR", "COMP-RANGE",
    "MOM-ACC", "MOM-RSL", "MOM-RSB", "VOL-DRY", "VOL-EXP",
    "FAIL-BRK", "FAIL-BASE", "FAIL-EMA20", "FAIL-SMA50", "FAIL-STRUCT",
)
