CREATE TABLE IF NOT EXISTS case_study_runs (
    id UUID PRIMARY KEY,
    status TEXT NOT NULL CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PARTIAL')),
    requested_from_date DATE NOT NULL,
    requested_to_date DATE NOT NULL,
    universe JSONB NOT NULL,
    requested_pattern_types JSONB NOT NULL DEFAULT '[]'::jsonb,
    requested_timeframes JSONB NOT NULL DEFAULT '[]'::jsonb,
    engine_version TEXT NOT NULL,
    configuration_version TEXT NOT NULL,
    feature_version TEXT NOT NULL,
    adjustment_version TEXT NOT NULL,
    trade_policy_version TEXT NOT NULL,
    selection_policy_version TEXT NOT NULL,
    point_in_time_policy JSONB NOT NULL,
    survivorship_bias_policy JSONB NOT NULL,
    securities_total INTEGER NOT NULL DEFAULT 0 CHECK (securities_total >= 0),
    securities_completed INTEGER NOT NULL DEFAULT 0 CHECK (securities_completed >= 0),
    securities_failed INTEGER NOT NULL DEFAULT 0 CHECK (securities_failed >= 0),
    cases_recorded INTEGER NOT NULL DEFAULT 0 CHECK (cases_recorded >= 0),
    failure_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
    requested_by UUID REFERENCES users (id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (requested_from_date <= requested_to_date)
);

CREATE TABLE IF NOT EXISTS case_studies (
    id UUID PRIMARY KEY,
    case_study_run_id UUID NOT NULL REFERENCES case_study_runs (id) ON DELETE RESTRICT,
    source_backtest_run_id UUID REFERENCES backtest_runs (id) ON DELETE SET NULL,
    source_backtest_entry_id UUID REFERENCES backtest_entries (id) ON DELETE SET NULL,
    replay_fingerprint TEXT NOT NULL,
    isin TEXT NOT NULL REFERENCES nse_equities (isin),
    historical_symbol TEXT,
    historical_company_name TEXT,
    pattern_class TEXT NOT NULL,
    pattern_type TEXT NOT NULL,
    variant TEXT,
    pattern_group TEXT,
    direction TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    lifecycle_state TEXT NOT NULL,
    pattern_start_date DATE,
    detection_date DATE NOT NULL,
    trigger_date DATE,
    confirmation_date DATE,
    entry_date DATE,
    exit_date DATE,
    entry_price NUMERIC,
    stop_price NUMERIC,
    target_price NUMERIC,
    exit_price NUMERIC,
    support_price NUMERIC,
    invalidation_price NUMERIC,
    measurements JSONB NOT NULL DEFAULT '{}'::jsonb,
    supporting_evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
    context JSONB NOT NULL DEFAULT '{}'::jsonb,
    exit_reason TEXT NOT NULL,
    completeness JSONB NOT NULL DEFAULT '{}'::jsonb,
    ambiguity JSONB NOT NULL DEFAULT '{}'::jsonb,
    review_status TEXT NOT NULL DEFAULT 'PENDING' CHECK (review_status IN ('PENDING', 'REVIEWED', 'REJECTED')),
    lineage JSONB NOT NULL,
    selection_policy_version TEXT NOT NULL,
    selection_reason TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (case_study_run_id, replay_fingerprint, selection_reason)
);

CREATE INDEX IF NOT EXISTS case_studies_catalog_idx
    ON case_studies (pattern_type, timeframe, direction, detection_date DESC, id);
CREATE INDEX IF NOT EXISTS case_studies_isin_idx ON case_studies (isin, detection_date DESC);

CREATE TABLE IF NOT EXISTS case_study_trade_results (
    case_study_id UUID PRIMARY KEY REFERENCES case_studies (id) ON DELETE RESTRICT,
    quantity INTEGER CHECK (quantity >= 0),
    deployed_capital NUMERIC,
    initial_risk NUMERIC,
    gross_pnl NUMERIC,
    costs NUMERIC,
    net_pnl NUMERIC,
    gross_return_pct NUMERIC,
    net_return_pct NUMERIC,
    gross_r_multiple NUMERIC,
    net_r_multiple NUMERIC,
    mfe_pct NUMERIC,
    mae_pct NUMERIC,
    fixed_horizon_outcomes JSONB NOT NULL DEFAULT '{}'::jsonb,
    completeness JSONB NOT NULL DEFAULT '{}'::jsonb,
    target_touch_date DATE,
    stop_touch_date DATE,
    same_session_policy TEXT NOT NULL,
    calculated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
